
server:
  port: 20011

spring:
  redis:
    host: 47.97.99.80
    port: 6379
    password: redispassword
    jedis:
      pool:
        max-active: 8
        min-idle: 8
        enabled: true
config:
  mq:
    endpoint: 127.0.0.1:40015
    producer-group: terra
    consumer-group: terra-crawler-server